### ISSUE TITLE
Orthanc and cornerstone not working

### ISSUE THREAD

**Issue by Annyv2** [chafey/cornerstoneWADOImageLoader#10]
Hello!

I need to serve some .dcm images on localhost, so I decided to go with Orthanc for that. I can see the file on localhost:8042/... perfectly, but when I put that link on the json (I'm using the Cornerstone web demo) It doesn't work. I used the nodejs that you mentioned for CORS but that didn't seem to work. 
I'm using XAMPP to serve the webpage, so I also tried to put CORS on Apache, but that didn't work either, do you have any suggestions for this issue?

THanks in advance!

**Comment by chafey** [comment]
I have integrated with Orthanc before and it works fine.  You either don't have CORS setup right, have the wrong Orthanc URL or have the wrong imageId in cornerstone.  Provide more detail on these things and also check the console log for errors and the network window for tips.  Also might want to post on the cornerstone platform google group where others can help

**Comment by Annyv2** [comment]
I just posted over thre https://groups.google.com/forum/#!topic/cornerstone-platform/yfM38j1DJrI Here's an image of what I get in the network window, I think it's accesing the file but there's no display

![network dicom](https://cloud.githubusercontent.com/assets/5016479/8263004/df2f2a2e-16a0-11e5-91e0-a3ccb9fdca6d.PNG)
![network dicom](https://cloud.githubusercontent.com/assets/5016479/8263005/df43c4a2-16a0-11e5-8c0d-800c3ffff5d1.PNG)

**Comment by chafey** [comment]
Is this issue resolved?  If so, please close

**Comment by chafey** [comment]
No response - closing this issue
