### ISSUE TITLE
Updating files and getting errors

### ISSUE THREAD

**Issue by agustingrigoriu** [chafey/cornerstoneWADOImageLoader#100]
Hello, I have updated this files to their last version:

- cornerstone-core - 0.11.0 - 2017-06-08

- cornerstone-math - 0.1.6 - 2017-06-09

- cornerstone-tools - 0.8.9 - 2017-06-09

- cornerstone-wado-image-loader - 0.14.6 - 2017-06-08

- CharLS.js - v2.0.1 - 2016-06-08

- cornerstone-wado-image-loader - 0.14.6 - 2017-06-08

- cornerstone-web-image-loader - 0.8.1 - 2017-06-08

- dicom-parser - 1.7.5 - 2017-06-02

After updating, I'm getting two errors, one of them is: **dicomParser.parseDicom is not a function** cornerstoneWADOImage loader is raising this error in the following sentence: `dataSet = dicomParser.parseDicom(byteArray);`
The second error I get is **cachedImage.imagePromise.reject is not a function** when I use: `cornerstone.imageCache.purgeCache();`

Thank you in advance for any solution you could suggest.

**Comment by swederik** [comment]
How are you loading these onto your webpage? NPM modules or directly via script tag?

The examples seem to work: https://rawgit.com/chafey/cornerstoneWADOImageLoader/master/examples/wadourimultiframe/index.html

so I don't know how to reproduce this.

**Comment by agustingrigoriu** [comment]
I'm loading them via script tag. And about the error **dicomParser.parseDicom is not a function** , I just tried with "cornerstone-wado-image-loader - 0.14.3" and It worked perfectly.

**Comment by swederik** [comment]
OK thanks for the report. I guess it's something with the packaging setup.

**Comment by swederik** [comment]
There's a minimal example here: https://github.com/chafey/byozfwv if you run the p4Connectivity example. I just updated the NPM dependencies and everything seems to work. Can you check this against yours and see what is different?

Thanks
