### ISSUE TITLE
CornerstoneImageLoadProgress not firing anymore

### ISSUE THREAD

**Issue by leonardorame** [chafey/cornerstoneWADOImageLoader#102]
This is related to [cornerstone #135](https://github.com/chafey/cornerstone/issues/135), the quick fix is replacing

    $(cornerstone).trigger('CornerstoneImageLoadProgress', {

with this:

    $(cornerstone.events).trigger('CornerstoneImageLoadProgress', {

Can anyone apply the fix?.

**Comment by swederik** [comment]
Where is this happening? It looks fine on master to me?

https://github.com/chafey/cornerstoneWADOImageLoader/search?utf8=%E2%9C%93&q=CornerstoneImageLoadProgress&type=

**Comment by leonardorame** [comment]
Mmm, I was using 0.14.3, I'm upgrading.
