### ISSUE TITLE
parsing of JPEG2000 is slow

### ISSUE THREAD

**Issue by ra00l** [chafey/cornerstoneWADOImageLoader#11]
I am looking at some JPEG2000 encoded images, and the parsing (using jsx.js from mozilla) is really slow; on top of this, it blocks the event loop for a couple of miliseconds.

I know there are some alternatives out there, like https://github.com/kripken/j2k.js and https://github.com/acdha/jp2-polyfill

When you went for jpx.js, did you had a look at the alternatives?
Any ideas on how to improve the parsing?

**Comment by chafey** [comment]
@jpambrun did the J2K work and is the best person to answer these questions:
https://github.com/jpambrun
https://github.com/OHIF/image-JPEG2000

**Comment by jpambrun** [comment]
Both these alternative are OpenJpeg compiled to JS. PDF.js started with
kripten's solution, but moved to the current pure JavaScript
implementation. I think both implementations would require some
modifications to support 16 bits signed images and I don't know if they
would be any faster.

I know it is currently too slow for large images such as CR, but,
unfortunately, I don't have enough free time to investigate this in the
near future.

**Comment by ra00l** [comment]
Thx Chris and Jean Francois.

I will have a look at ways to optimize the loading. This is my pain right now.

Will let you guys know if I find any issues.

Thanks again!

**Comment by Neuroforge** [comment]
This issue still appears to be a problem for me.

It could be related to anther issue i am having with JP2 images

https://github.com/cornerstonejs/cornerstoneWADOImageLoader/issues/238

**Comment by pieper** [comment]
Did anyone post an anonymized set of images that are validly encoded but slow with the the current code?  Can you add a link here?

**Comment by Neuroforge** [comment]
@pieper There is an example image on https://github.com/cornerstonejs/cornerstoneWADOImageLoader/issues/238 however, there are other issues with this type of image. i.e. It does not have the getCanvas method available.

**Comment by pieper** [comment]
I saw that link, but that data is not valid according to Mathieu.  I was hoping we had known-valid ones for any speed testing.

**Comment by Neuroforge** [comment]
@pieper Yeah, no one wants to go near that issue. :D

**Comment by pieper** [comment]
Right - if the data's not valid I don't really consider it an issue  ; )
