### ISSUE TITLE
Webpack require cornerstone-core issue

### ISSUE THREAD

**Issue by drozdzynski** [chafey/cornerstoneWADOImageLoader#110]
When I require cornerstone modules in my app:
```
window.cornerstone = require('cornerstone-core');
window.cornerstoneTools = require('cornerstone-tools');
window.cornerstoneMath = require('cornerstone-math');
window.dicomParser = require('dicom-parser');
window.jpeg = require('jpeg-lossless-decoder-js');
window.cornerstoneWADOImageLoader = require('cornerstone-wado-image-loader');
```

**cornerstoneWADOImageLoader** is running with own **cornerstone-core** instance:
```
module.exports = factory(require("jquery"), require("cornerstone-core"), require("dicom-parser"));
```

so when **cornerstoneWADOImageLoader** calls ```cornerstone.registerImageLoader('dicomweb', loadImage);``` it not calls it in mine ```cornerstone-core``` instance.

I use **webpack 2** to compile JS.

**Comment by swederik** [comment]
Yeah I've run into this too and it's definitely a problem we need to fix...

**Comment by deminoth** [comment]
How about adding `cornerstoneWADOImageLoader.setCornerstoneInstance(cornerstone)`? I can make some PR if it seems ok.

**Comment by deminoth** [comment]
Nevermind. I found a workaround:
```js
import * as cornerstoneWADOImageLoader from 'cornerstone-wado-image-loader/dist/cornerstoneWADOImageLoader'
```

**Comment by swederik** [comment]
This should be fixed now. Use:

````javascript
cornerstoneWADOImageLoader.external.cornerstone = cornerstone;
````
