### ISSUE TITLE
Display DICOM images with cornerstoneWADOImageLoader, but lose grayscale

### ISSUE THREAD

**Issue by fjydegit** [chafey/cornerstoneWADOImageLoader#124]
![02](https://user-images.githubusercontent.com/19260548/29910328-169a18cc-8e5c-11e7-9c08-5eb107b40139.png)
![01](https://user-images.githubusercontent.com/19260548/29910327-11a5f84a-8e5c-11e7-9f3c-8dc5cd5aa414.png)
This is the same DICOM file, and my code is the same as the demo code. I don't know why it's so different. I hope you can give some advice.Thank you very much.

**Comment by swederik** [comment]
I think your file has invalid smallest and largest pixel values. I guess the demo site is fixing this for you following a recent commit. Can you update to the latest version and try again?

**Comment by fjydegit** [comment]
![11](https://user-images.githubusercontent.com/19260548/30725645-c8d2c39a-9f78-11e7-95c6-906803a80a3e.png)
Yes, I have used the latest version. It works well. Thank you very much！
