### ISSUE TITLE
Measurement Tools prints NaN

### ISSUE THREAD

**Issue by algates90** [chafey/cornerstoneWADOImageLoader#131]
For certain images, the Length gets displayed as pixels instead of mm and Angles gets displayed as NaN.
I could see the difference in files that

Length properly measured image has the dicom tag - PixelSpacing(0028,0030)
NaN cases has dicom tag - ImagerPixelSpacing(0018,1164)

How can this be handled in cornerstone ? Do we already have a solution ?

**Comment by diego0020** [comment]
My approach is registering a [metadata provider](https://github.com/chafey/cornerstone/blob/master/src/metaData.js)  and setting  *rowPixelSpacing* and *columnPixelSpacing* from ImagerPixelSpacing if it is present.

**Comment by chafey** [comment]
@algates90 projection radiographs require manual calibration to correctly do length measurements.  You can force cornerstone to incorrectly use ImagerPixelSpacing as @diego0020 suggests, but your measurements will be wrong.

**Comment by dannyrb** [comment]
Just curious, would creating a "calibration tool" that sets these values
based on a known length in the image suffice? Or is it more complicated
than that?

Ie. What values need to be known/calibrated to create accurate measurements?

**Comment by chafey** [comment]
@dannyrb the correct way to solve this is for the xray tech to place a physical object of a known size (e.g. 10mm diameter circle)  at the correct depth during the xray and then provide a tool to calculate the row/column pixel spacing for the image by measuring that object.  This should be done in cornerstoneTools, not here in the loader.  Manual calibrations should be handled separately from the metadata provider, appropriate infrastructure put in place to manage them in cornerstoneTools and updates to the tools themselves.  Not a huge task, but not trivial

**Comment by dannyrb** [comment]
Thanks for the response @chafey! I've created a related issue in `chafey/cornerstoneTools` @algates90. Feel free to carry on the conversation there. I'm marking this issue as closed in this repository.
