### ISSUE TITLE
Image loader fails on implicit hostname

### ISSUE THREAD

**Issue by zachmullen** [chafey/cornerstoneWADOImageLoader#16]
When passed a url such as: `dicomweb:///api/v1/file/55cca47e20c30d6b680f1be9/download`, the image loader attempts to fetch from `http://api/v1/file/55cca47e20c30d6b680f1be9/download `, and by removing the leading slash it becomes an invalid URL.

**Comment by chafey** [comment]
the loader passes whatever is after the : to the XHR, try this:
dicomweb:/api/v1/file/55cca47e20c30d6b680f1be9/download

**Comment by zachmullen** [comment]
That fixed it, thanks @chafey !
