### ISSUE TITLE
CornerstoneImageLoadProgress does not working

### ISSUE THREAD

**Issue by onluiz** [chafey/cornerstoneWADOImageLoader#17]
Hi everyone.

I am trying to use CornerstoneImageLoadProgress and it's just not working. I also tried to execute this function from cornerstoneWADOImageLoader demo (http://rawgit.com/chafey/cornerstoneWADOImageLoader/master/examples/index.html) and again I coud not make that work.

Is there some special condition to make this event work?

Did I posted it on the right place?

Thanks for the help.

**Comment by chafey** [comment]
CornerstoneImageLoadProgress depends on the lengthComputable browser feature that is currently only supported by Firefox:
https://developer.mozilla.org/en-US/docs/Web/API/ProgressEvent/lengthComputable

**Comment by leonardorame** [comment]
Really?, I'm using it in both Firefox and Chrome, and it's workling without an issue. I use this with WebImageLoader and WADOImageLoader. 

Chris is right regarding the Content-Length property.

**Comment by chafey** [comment]
Oh thats good news, I didn't realize it worked on Chrome too!  @onluiz Can you try adding the Content-Length parameter and let us know how it goes?

**Comment by chafey** [comment]
Any update on this?  Will close if I don't hear back in a week

**Comment by onluiz** [comment]
Hi Chris. With Content-Length worked very well :) thank you

**Comment by leonardorame** [comment]
This is working, I've tested and can confirm it works on Chrome, FF, IE11, Android, I don't know if it works on iOS.

**Comment by chafey** [comment]
Good to hear!  Closing
