### ISSUE TITLE
JPegLossless and RGB images

### ISSUE THREAD

**Issue by leonardorame** [chafey/cornerstoneWADOImageLoader#18]
Hi Chris, just to say the new JPEGLossless decoder has the same issue #15 as the RLE.

**Comment by chafey** [comment]
Strange - can you send me an example image to debug/test with?

**Comment by leonardorame** [comment]
Sure:

http://181.165.182.82:8083/cgi-bin/wado/instance/?objectUID=1.3.46.670589.14.3000.310.110786.2.20150903102408.1000000137&contentType=dicom

To get the same image's RLE version

http://181.165.182.82:8083/cgi-bin/wado/instance/?objectUID=1.3.46.670589.14.3000.310.110786.2.20150903102408.1000000137&contentType=dicom/rle

**Comment by chafey** [comment]
I am pretty sure I am handling this properly - I think the bug may be with the JPEGLossless decoder itself (the RLE bug you reference was in the RLE decoder so this would be consistent).  Can you file a bug over there and see rii-mango says?  Keeping this open until we know more

**Comment by chafey** [comment]
BTW - I confirmed that the image displays properly with two other viewers so the image is not in question

**Comment by leonardorame** [comment]
Wow, Github is great, I just pasted this issue in rii-mando and a note was added here automatically, that's how software should work.

**Comment by rii-mango** [comment]
Sorry for late reply.  Yes, JPEGLosslessDecoderJS doesn't yet handle RGB data.  Currently, it collapses it into intensity data.  This is high on my todo list and hopefully I can get to it this week...

**Comment by rii-mango** [comment]
Version 1.2 of JPEGLosslessDecoderJS supports RGB data.  Please give it a try.  Output is a byte array in the form RGBRGBRGB...

**Comment by leonardorame** [comment]
@rii-mango test passed!, it works perfectly.

**Comment by leonardorame** [comment]
@chafey the fix by @rii-mango works, but now jpeglossless and rle has the same error as in https://github.com/chafey/cornerstoneWADOImageLoader/issues/20

**Comment by chafey** [comment]
Just pushed version 0.7.2 with the latest JPEGLossless decoder and a fix for multiframe (requires latest dicomParser)

**Comment by leonardorame** [comment]
Well done!, JPEGLossLess test passed on RGB single and multiframe, also on grayscale (CT, MR, CR) images.

**Comment by chafey** [comment]
Ok great!  Closing
