### ISSUE TITLE
RLELossLess Images

### ISSUE THREAD

**Issue by jolann69** [chafey/cornerstoneWADOImageLoader#19]
Hi, 
Thanks for your great job.

I need to add RleLossLess Image support to cornestone.
I have done the following things:
Create a function extractRLEPixels, inspired from 
http://marklomas.net/ch-egg/articles/rlejs.htm

function extractRLEPixels(dataSet, width, height, frame)
    {
        try 
        {
            var compressedPixelData = dicomParser.readEncapsulatedPixelData(dataSet, dataSet.elements.x7fe00010, frame);
            var result = new Array;
            if (compressedPixelData.length == 0)
                return result;

            if ((compressedPixelData.length % 2) != 0) {
                alert("Invalid RLE Pixeldata");
                return;
            }

            var length = compressedPixelData.length;
            for (var i = 0; i < length; i += 2) {
                var val = compressedPixelData[i];
                var count = compressedPixelData[i + 1];
                for (var c = 0; c < count; c++)
                    result[result.length] = val;
            }
            return result;
        }
        catch(err)
        {

        }
    }

Then in your existing function extractStoredPixels, i add:

if (transferSyntax === "1.2.840.10008.1.2.5")
        {
            return extractRLEPixels(dataSet, width, height, frame);
        }

But it doesn't work, i have an outofrange exception when i try to decode a Dicom Image in rle.
Did i miss something ? Have you got an idea ? 

Thanks
Thomas

**Comment by chafey** [comment]
RLE support was added a few weeks back - get latest and try it!

**Comment by jolann69** [comment]
Yes, it works !
Thanks
Thomas
