### ISSUE TITLE
RLE Multiframe error

### ISSUE THREAD

**Issue by leonardorame** [chafey/cornerstoneWADOImageLoader#20]
Hi again, I'm getting en error while trying to load an RLE multiframe image using cornerstoneWADOImageLoader, here's the error:

    RangeError: argument 1 accesses an index that is out of range
    Stack trace:
    decode16@http://127.0.0.1/displaystudy/js/cornerstone/cornerstoneWADOImageLoader.js:505:23
    decodeRLE@http://127.0.0.1/displaystudy/js/cornerstone/cornerstoneWADOImageLoader.js:453:7
    decodeTransferSyntax@http://127.0.0.1/displaystudy/js/cornerstone/cornerstoneWADOImageLoader.js:578:14
    makeGrayscaleImage@http://127.0.0.1/displaystudy/js/cornerstone/cornerstoneWADOImageLoader.js:3739:29
    createImageObject@http://127.0.0.1/displaystudy/js/cornerstone/cornerstoneWADOImageLoader.js:255:14
    xhrRequest/xhr.onreadystatechange@http://127.0.0.1/displaystudy/js/cornerstone/cornerstoneWADOImageLoader.js:4105:30

The image is this:

http://181.165.182.82:8083/cgi-bin/wado/instance/?objectUID=2.16.840.1.113662.5.8796823269005.3.124.1441314757&contentType=dicom/rle

I must add using ExplicitLittleEndian TS doesn't raises the error, please check:

http://181.165.182.82:8083/cgi-bin/wado/instance/?objectUID=2.16.840.1.113662.5.8796823269005.3.124.1441314757&contentType=dicom/explicit

Leonardo.

**Comment by chafey** [comment]
Required a fix to the dicomParser library (1.1.7) - get that and it should work (0.7.2 of this library references this new version via bower)

**Comment by leonardorame** [comment]
You are right, it works as expected after updating dicomParser.

**Comment by chafey** [comment]
Good to hear!  Closing
