### ISSUE TITLE
Wrongly displayed image

### ISSUE THREAD

**Issue by leonardorame** [chafey/cornerstoneWADOImageLoader#25]
Here's a new image generated from a GE VIVID E9 Ultrasound Modality that's correctly displayed in our Synapse PACS, but wrong in Cornerstone (also Weasis and Radiant cannot display it correctly).

http://45.63.8.72/cgi-bin/wado/instance/?objectUID=1.2.840.113619.2.239.8938.1443110370.0.812.8&contentType=dicom

Regards,
Leonardo.

**Comment by chafey** [comment]
Osirix does not display it properly either.  If the image is in fact valid, the bug would likely be in the JPEG Lossless decoder here: https://github.com/rii-mango/JPEGLosslessDecoderJS Maybe try creating an issue there?

**Comment by chafey** [comment]
@leonardorame any update on this issue?  Please close if you can determine it is not a cornerstone issue

**Comment by leonardorame** [comment]
I'll close, as I can reproduce it using different tools, this issue is not a Cornerstone one.
