### ISSUE TITLE
dicomParser.readSequenceItem: item tag (FFFE,E000) not found at offset...

### ISSUE THREAD

**Issue by leonardorame** [chafey/cornerstoneWADOImageLoader#33]
When trying to open some files with the cornerstoneWADOImageLoader 0.9.2 in combination with dicomParser 1.3.0 the exception "dicomParser.readSequenceItem: item tag (FFFE,E000) not found at offset..." is raised.

Please go to `examples/wadouri/index.html` and open this file: `http://190.210.68.13:8888/cgi-bin/wado/instance/?objectUID=1.3.12.2.1107.5.2.37.48929.201510081009333606404861&contentType=dicom`.

**Comment by chafey** [comment]
Can you provide the problematic file for debugging?

**Comment by leonardorame** [comment]
Sure, I can send it to an email address, or you can do a `curl -o file.dcm "http://190.210.68.13:8888/cgi-bin/wado/instance/?objectUID=1.3.12.2.1107.5.2.37.48929.201510081009333606404861&contentType=dicom"`.

If you prefer the email option, please give me one and I'll send you the file.

**Comment by leonardorame** [comment]
Hi Chris, did you check this?.

**Comment by chafey** [comment]
I just tried downloading the file and got a 500 internal server error - can you check it again?  sorry for the delay

**Comment by chafey** [comment]
Think this was a regression in dicomParser 1.3 - try version 1.4 and see if it fixes it

**Comment by chafey** [comment]
FYI - latest version 0.10.0 is referencing version 1.4 of dicomParser

**Comment by leonardorame** [comment]
After the upgrade to 0.10.0 and dicomParser 1.4 it started working as expected again. 

Thank you very much!.
