### ISSUE TITLE
Replace jpx by libopenjpeg for JPEG 2000 decoding

### ISSUE THREAD

**Issue by jpambrun** [chafey/cornerstoneWADOImageLoader#37]
I'm not submitting a pull request because I don't have a setup to test it correctly and I don't really know how you want to organize the source code.

The latest minified release is here:

https://github.com/jpambrun/openjpeg/releases

The interface is somewhat similar to jpx:

``` javascript
image = Module.opj_decode(compressedPixelData);
var j2kWidth = image.sx;
var j2kHeight = image.sy;
var pixelData = new Int16Array(image.pixelData);
```

image.pixelData is actually an Int32Array and if the image is in color, the pixels are interleaved as follows : RGBRGBRGB...

**Comment by chafey** [comment]
Integrated
