### ISSUE TITLE
Structured report

### ISSUE THREAD

**Issue by jssuttles** [chafey/cornerstoneWADOImageLoader#39]
Hey,
I love the work you've done here.
I'm currently working to build an online viewer and I've run into a problem with Structured Reports. This WADO image loader doesn't handle it very gracefully. (No pixel representation or bits allocated). I can probably detect whether it's a structured report before loading it, however, after that I don't know what to do with it. It's not exactly a PDF. Any ideas would be greatly appreciated.

**Comment by chafey** [comment]
DICOM SR is a complex document which contains information about one or more images.  Since cornerstone deals with displaying images in a single viewport, direct interpretation of DICOM SR is outside the scope of cornerstone and should therefore be done at a higher level.
