### ISSUE TITLE
CornerstoneImageLoadProgress's broken in v0.12.0

### ISSUE THREAD

**Issue by leonardorame** [chafey/cornerstoneWADOImageLoader#43]
Hi Chris, I found cornerstoneImageLoadProgress event is not sending the imageId param, to fix this, please change the line 57 of loadImage.js from this:

    var xhrRequestPromise =  loader(parsedImageId.url);

To this:

    var xhrRequestPromise =  loader(parsedImageId.url, imageId);

Regards,
Leonardo.

**Comment by chafey** [comment]
Fixed in 0.12.1, can you verify?

**Comment by leonardorame** [comment]
Tested on 0.13.0 and it works as expected. Closing this right now.
