### ISSUE TITLE
Incorrect WW/WC adjustment for some CR series

### ISSUE THREAD

**Issue by hardmaster92** [chafey/cornerstoneWADOImageLoader#45]
Some CR series like [this one](http://www10.zippyshare.com/v/LqjPyuY0/file.html) appear almost white and adjusting WW/WC manually doesn't seem to have any effect on the viewport. I can open the dicom file and it looks perfect with any desktop viewer (like microdicom for example) but cornerstone seems to have problems with it. I'm not sure if it's issue related to WADOImageLoader or dicomParser but the problem exists in my implementation and also when I'm using the cornerstoneWADOImageLoader examles.

**Comment by chafey** [comment]
Hi - This image has a VOI LUT and the default behavior is to display the image with the VOI LUT.  When the VOI LUT is displayed, the image appears white.  I suspect the VOI LUT is not standards compliant as some vendors generate invalid VOI LUTs.  You can disable the display of the VOI LUT by setting the voiLUT property of the viewport to undefined
