### ISSUE TITLE
JPEGBaseline color images rendered wrong

### ISSUE THREAD

**Issue by bisol** [chafey/cornerstoneWADOImageLoader#46]
Hi, 

Cornerstone is rendering this US image in shades of green/magenta
**(REMOVED because it appeared to have PHI)**

I've been able to reproduce this by converting images to JPEGExtended (1.2.840.10008.1.2.4.51) transfer syntax with dcmtk's "dcmcjpeg.exe +ee"

It seems the JPEGBaseline decoder is aplying an unecessary color transform to the image: setting colorTransform to false in decoders/external/jpeg.js:955 fixes this:

``` javascript
case 3:
    // The default transform for three components is true
    colorTransform = false; //true;
```

I know DICOM is full of weird corner cases, do you think this is a valid solution?

**Comment by swederik** [comment]
Thanks for the report. I removed the image from your post since it appeared to have PHI in it. It does still appear in green / magenta, though, so I have tagged this as a bug.

**Comment by swederik** [comment]
You were correct. It appears that the jpeg-jg library is applying a YCbCr -> RGB color transform internally. We don't want this to happen since we handle the color space conversion afterwards. I have just added ````jpeg.colorTransform=false```` flag to prevent this, rather than editing the library code itself.
