### ISSUE TITLE
No Image Rendering

### ISSUE THREAD

**Issue by mattsones** [chafey/cornerstoneWADOImageLoader#50]
I'm attempting to render an image from a base64 string stored in a database. dicomParser is correctly reading the data, but the image loader isn't rendering anything. I always get a canvas with zero height and width, despite the fact that the image data from dicomParser is correctly showing 600 and 800 for height and width, respectively. Any thoughts on where to start troubleshooting?

Here is the function I'm using to convert my base64 string to a file:

```
//Load image function
function loadAndViewImage(imageId,element) {
    cornerstone.loadImage(imageId).then(function(image) {
        console.log(image);
        var viewport = cornerstone.getDefaultViewportForImage(element, image);
        
        cornerstone.displayImage(element, image, viewport);
    }, function(err) {
        alert(err);
    });
}

//Convert base64 string from database to array parts for new File()
function b64toArrayParts(b64Data, sliceSize) {
  sliceSize = sliceSize || 512;

  var byteCharacters = window.atob(b64Data);
  var byteArrays = [];

  for (var offset = 0; offset < byteCharacters.length; offset += sliceSize) {
    var slice = byteCharacters.slice(offset, offset + sliceSize);

    var byteNumbers = new Array(slice.length);
    for (var i = 0; i < slice.length; i++) {
      byteNumbers[i] = slice.charCodeAt(i);
    }

    var byteArray = new Uint8Array(byteNumbers);

    byteArrays.push(byteArray);
  }

  return byteArrays;
}

if (row.Name.endsWith('.dcm')) {
    //Get base64 string, and create File.
    var Base64content = (row.Body.realBlobValue!==undefined) ? row.Body.realBlobValue.asByteArray : row.Body.asByteArray;
    var arrayParts = b64toArrayParts(Base64content);
    var file = new File(arrayParts,row.Name,{type:'image/dicom'});
    console.log(file);

        //Create and add element to our field
	var dicomDiv = $('<div>')
	    .addClass('dicom-image')
	    .attr('id','dicomImage')
	    .css({height: '512px', width: '512px'});
	field.element.append(dicomDiv);

    // Enable element with cornerstone
	var csElement = dicomDiv.get(0);
    cornerstone.enable(csElement);
    
   // Load image.
    var imageId = cornerstoneWADOImageLoader.fileManager.add(file);
    loadAndViewImage(imageId,csElement);
}
```

**Comment by chafey** [comment]
Code looks fine, do you see any errors in the console log?  If not, try setting some breakpoints.  If possible, you should have your server convert from base64 to DICOM P10 and use the wadouri loader.  This will require less network bandwidth (base 64 increases size by 50%) and allow you to leverage the cornerstone cache and on demand loading mechanism that you lose by using the dicomfile approach the way you are doing.

**Comment by mattsones** [comment]
Thanks.

I think I actually have the files on the server in DICOM P10, but I keep getting CORS errors that I can't get around with the wadouri loader. Know anyone who has done DICOM integration with Salesforce?

**Comment by chafey** [comment]
I don't know anyone that has integrated DICOM with Salesforce.  You can fix CORS issues with a proxy if you can't get the server that stores the DICOM to add the right headers

**Comment by chafey** [comment]
Can you please close unless you think there is an issue in cornerstone>?
