### ISSUE TITLE
Memory issue with image decoding

### ISSUE THREAD

**Issue by mabuzer** [chafey/cornerstoneWADOImageLoader#51]
I tried to use cornerstone to load SC study with JPEG-LS (Transfer Syntax: 1.2.840.10008.1.2.4.70), images have a high resolution like (4192x5081), study contains around 15 images, memory allocated to view this study sometimes exceed 2 Gb, average size for each image is around 8 Mb, bitsAllocated is 8 bit, photometric is MONOCHROME2.

I used latest `charLS-DynamicMemory-browser.js` but still the same, 

My question is this considered a memory leak, or it's normal behavior based on image dimensions, and if so do you think changing the transfer syntax to JPEG-2000 would fix the memory leak.

Thanks.

**Comment by chafey** [comment]
Unfortunately this is normal behavior for both the JPEG-LS and the OpenJPEG JPEG2000 codecs.  The reason for this is both of these codecs are EMSCRIPTEM builds of C++ code and need to allocate memory to support the C++ runtime and heap and never returns this memory to the browser.  The solution is to create native JS implementations of these codecs and one exists for JPEG2000 (the PDF.js based one), but it doesn't decode all image types properly (the OpenJPEG 2000 one is far more complete)

**Comment by mabuzer** [comment]
It seems to be related to `EMSCRIPTEM` and `Chrome` because when testing on `Firefox` things are better, it peaks to around 1.5 Gb, then it goes down to half like 750 Mb,,,,

Thanks for your quick reply, but I guess I have to close it now.

**Comment by chafey** [comment]
Firefox has much better support for ASM.JS than chrome - performance (and memory management) should both improve as everyone converges on Web Assembly.  Closing...
