### ISSUE TITLE
dataSetCacheManager return wrong type multiframe image (dev branch)

### ISSUE THREAD

**Issue by lambacini** [chafey/cornerstoneWADOImageLoader#52]
for dev branch

if image multiframe and already loaded. (XA,uSG)

cornerstoneWADOImageLoader.wadouri.dataSetCacheManager.load function return type of dataset

**alreadyLoadedpromise.resolve(loadedDataSets[uri].**dataSet**);**

but 

loadDataSetFromPromise function use byte array and convert dataset again.

**var byteArray = new Uint8Array(dicomPart10AsArrayBuffer);
var dataSet = dicomParser.parseDicom(byteArray);**

**Comment by jssuttles** [comment]
Ran into this just now.

**Comment by chafey** [comment]
Fixed in most recent push - can you verify?  Thanks for reporting

**Comment by chafey** [comment]
Can you please verify and close if fixed?  Thanks

**Comment by lambacini** [comment]
I'm sorry for the late reply. 
Yes problem fixed.
