### ISSUE TITLE
Image not displaying properly

### ISSUE THREAD

**Issue by surajem** [chafey/cornerstoneWADOImageLoader#55]
Hi
      When i am trying to load image using cornerstoneWADOImageLoader it  is coming different  
![cor](https://cloud.githubusercontent.com/assets/19304891/19435933/095459d2-948b-11e6-8812-4c135988178f.png)

But when tried to load from Sante Dicom viewer  it is viewing properly 
when i use  this version of the file  cornerstone.js  /*! cornerstone - v0.8.4 - 2015-09-12 | (c) 2014 Chris Hafey | https://github.com/chafey/cornerstone */ it works fine 

but when i use this version cornerstoneWADOImageLoader.min.js
/*! cornerstone-wado-image-loader - v0.10.1 - 2016-05-04 | (c) 2014 Chris Hafey | https://github.com/chafey/cornerstoneWADOImageLoader */
it does not work 
Do i need to make any changes  please let me know 
here is zip file for it
[TEST.zip](https://github.com/chafey/cornerstoneWADOImageLoader/files/533497/TEST.zip)

Regards
Suraj

**Comment by swederik** [comment]
I suppose something must have been wrong with our YBR_FULL or 1.2.840.10008.1.2.1 [Explicit VR Little Endian] handling. The image appears to display properly for me now, so I'll close the issue.

Thanks for the report!
