### ISSUE TITLE
Use faster lossless jpeg decoder.

### ISSUE THREAD

**Issue by yvoronen** [chafey/cornerstoneWADOImageLoader#56]
Chris, we were able to speedup lossless decoding significantly. 
Since you are not an official fork of rii-mango's repo, here is a link for the PR.

https://github.com/rii-mango/JPEGLosslessDecoderJS/pull/10

**Comment by swederik** [comment]
Thanks for letting us know! I've updated to the latest from the JPEGLosslessDecoderJS project.
