### ISSUE TITLE
Cannot load these dicom files

### ISSUE THREAD

**Issue by gokhandilek** [chafey/cornerstoneWADOImageLoader#61]
Hi, 

I am trying to load these files (attached - removed) using cornersonewadoimageLoader. But I cannot load it on the canvas.

I don't have any issue loading other files.

Could you please me know what maybe causing this?

I am using the replicate of [cornerstonedemo](http://chafey.github.io/cornerstoneDemo/)

Thank you so much.

**Comment by chafey** [comment]
Good news - these images are loading properly using a newer version of openjpeg - hoping to push this out soon

**Comment by gokhandilek** [comment]
Oh nice. Thank you very much for the updates. Much appreciate it.
I have never had a close look at wadoimageloader.  Is openjpeg included within this library?

**Comment by swederik** [comment]
Closing because these are apparently working now.
