### ISSUE TITLE
how to show overlay dicom file

### ISSUE THREAD

**Issue by DMIAOCHEN** [chafey/cornerstoneWADOImageLoader#63]
hello, how to show overlay file, like this file. [overlay dicom file](https://cdn.rawgit.com/DMIAOCHEN/RawGit/4f217dcf/Dicoms/overlay.DCM)

**Comment by swederik** [comment]
Hi,

We don't have support for this just yet, but it is on our radar!

Cheers,

Erik

**Comment by DMIAOCHEN** [comment]
OK, thanks for reply.
