### ISSUE TITLE
grayscale images

### ISSUE THREAD

**Issue by snagytx** [chafey/cornerstoneWADOImageLoader#7]
The text embedded in the grayscale DICOM images might become unreadable. the minPixelValue/maxPixelValue are 0/254 if I force them to 0/255 everything works fine.

**Comment by chafey** [comment]
snagtyx - i somehow missed this - sorry!  Does this issue still exist for you?  There was a change in cornerstone core that was made a few months back that may have fixed it

**Comment by chafey** [comment]
snagtyx - can you let us know if this issue still exists?

**Comment by snagytx** [comment]
I'm sorry but I can't test with right now, if you think it's fixed already
feel free to close this issue and I'll re-open it or create a new one when
I update to the latest release if the issue is still there.
