### ISSUE TITLE
Image Decoding

### ISSUE THREAD

**Issue by MAhmedSaeed** [chafey/cornerstoneWADOImageLoader#76]
the decoding problem reproduced in this version

dicom image
https://drive.google.com/file/d/0B7SF2JRjP5AtNzZESDg5enJwUTA/view

cornerstoneWADOImageLoader
![untitled](https://cloud.githubusercontent.com/assets/17268318/24747437/a286ec8e-1abc-11e7-8dfe-cba9e1674ecf.jpg)

other viewer
![untitled](https://cloud.githubusercontent.com/assets/17268318/24747496/d2fd1276-1abc-11e7-9516-6d871f2cfea5.jpg)

**Comment by swederik** [comment]
Thanks for the report!

**Comment by jpambrun** [comment]
This is most likely because of this :
```
(0028,0106) US 0                                        #   2, 1 SmallestImagePixelValue
(0028,0107) US 0                                        #   2, 1 LargestImagePixelValue
```

**Comment by swederik** [comment]
Yep you seem to be right. It works fine on this branch: https://rawgit.com/chafey/cornerstoneWADOImageLoader/issue73/examples/dicomfile/index.html
