### ISSUE TITLE
Artifacts exist in the decompressed image

### ISSUE THREAD

**Issue by evren217** [chafey/cornerstoneWADOImageLoader#83]
We have this issue with JPEG Baseline lossy process 2 & 4.

Here is the artifacts shown in cornerstone:

![cornerstone](https://cloud.githubusercontent.com/assets/4920551/25454385/459d239c-2a9a-11e7-876c-c842ba972c72.jpg)

Here is the image that looks good in another viewer:

![horos](https://cloud.githubusercontent.com/assets/4920551/25454471/8902ee1e-2a9a-11e7-972f-7daccefb183b.jpg)

[problem image.dcm.zip](https://github.com/chafey/cornerstoneWADOImageLoader/files/959640/problem.image.dcm.zip)

How to reproduce:

Unpack the attached dicom file and import it into the demo:
https://rawgit.com/chafey/cornerstoneWADOImageLoader/master/examples/dicomfile/index.html

**Comment by jpambrun** [comment]
The LargestImagePixelValue is incorrect

                     SmallestImagePixelValue: 0
                      LargestImagePixelValue: 2729
                            RescaleIntercept: -1024
                                RescaleSlope: 1

3DSlicer reports min/max of -1024/1713

1713 + 1024 = 2737  > 2729 thus causing issue with the lut.

It's effectively returning NaNs (or undefined) which are treated as zeros
as lookups are made outside of the lut range.

**Comment by jpambrun** [comment]
This is a duplicate  of #76 and #73.
