### ISSUE TITLE
Dicom file example does not show progress correctly

### ISSUE THREAD

**Issue by kofifus** [chafey/cornerstoneWADOImageLoader#84]
see:
https://rawgit.com/chafey/cornerstoneWADOImageLoader/master/examples/wadouri/index.html

As far as I can tell the problem is here: https://github.com/chafey/cornerstoneWADOImageLoader/blob/master/examples/dicomfile/index.html#L275

`$(cornerstone).bind('CornerstoneImageLoadProgress', function(eventData) {`

should be:

`$(cornerstone).bind('CornerstoneImageLoadProgress', function(event, eventData) {`

thx

**Comment by swederik** [comment]
Fixed, thanks!
