### ISSUE TITLE
Where is the URL from where we get the dicom images?

### ISSUE THREAD

**Issue by ManuelTinoco** [chafey/cornerstoneWADOImageLoader#9]
Hi ,

Could you tell me exactly where is the url of the server from Dicom images in cornerstone getting to cornerstoneWADOloader.js for see after?

Regards ,
Manuel

**Comment by chafey** [comment]
I don't understand the question, can you please elaborate with more detail?

**Comment by chafey** [comment]
Did you resolve your issue?  If so, please close
