### ISSUE TITLE
image.webWorkerTimeInMS undefined

### ISSUE THREAD

**Issue by kofifus** [chafey/cornerstoneWADOImageLoader#90]
webWorkerTimeInMS is used in the samples (ie [here](https://rawgit.com/chafey/cornerstoneWADOImageLoader/master/examples/wadouri/index.html) on the bottom right), and in the code (ie [here](https://github.com/chafey/cornerstoneWADOImageLoader/blob/master/src/imageLoader/createImage.js#L84)), but is never populated.

In fact it does not exist in cornerstoneWADOImageLoaderWebWorker.js

**Comment by swederik** [comment]
Thanks for the report, I guess it must have been removed at some point, possibly accidentally...

**Comment by swederik** [comment]
I just removed the references to this, thanks.
