### ISSUE TITLE
dataSetCacheManager.isLoaded code

### ISSUE THREAD

**Issue by kofifus** [chafey/cornerstoneWADOImageLoader#92]
in:

https://github.com/chafey/cornerstoneWADOImageLoader/blob/master/src/imageLoader/wadouri/loadImage.js#L64-L66

The code executed if dataSetCacheManager.isLoaded

Is identical to the code executed if it is not (https://github.com/chafey/cornerstoneWADOImageLoader/blob/master/src/imageLoader/wadouri/loadImage.js#L69)

Is this a bug ?

Thx!

**Comment by swederik** [comment]
Yep certainly looks like a bug. I guess we should be using dataSetCacheManager.get or something instead. Thanks for the report!

**Comment by swederik** [comment]
This was fixed recently: https://github.com/chafey/cornerstoneWADOImageLoader/blob/master/src/imageLoader/wadouri/loadImage.js#L97
