### ISSUE TITLE
Uncaught TypeError: Cannot read property 'metaData' of undefined

### ISSUE THREAD

**Issue by hashitha** [chafey/cornerstoneWADOImageLoader#97]
This is coming up and doesn't seem to work now

![image](https://cloud.githubusercontent.com/assets/10569142/26612030/c39894ba-45e4-11e7-9a48-22833f1ac782.png)

**Comment by hashitha** [comment]
This is working fine in 0.14.2

**Comment by swederik** [comment]
This should be fixed now.

**Comment by hashitha** [comment]
Thanks. It is working now
